# Site settings
title: Portfolio of Chuck Bergeron
email: chuck@chuckbergeron.io
description: "Chuck Bergeron creates VR experiences, videogames and apps in Vancouver, BC"

name: chuckbergeron
markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/blog/page/:num"

exclude: ['deploy.sh', 'Gemfile', 'Gemfile.lock']
gems: [jekyll-assets, uglifier, jekyll-slim, slim, jekyll-paginate]

assets:
  assets:
    - "application.css"
    - "*.svg"
    - "*.woff"
    - "*.woff2"
    - "*.eot"
    - "*.ttf"
    - "*.js"
    - "*.mp4"
    - "*.png"
    - "*.jpg"
    - "*.gif"

collections:
  work:
    output: true
    permalink: /:collection/:path/
