# Site settings
title: Portfolio of Chuck Bergeron
email: chuck@chuckbergeron.io
description: "The portfolio of Chuck Bergeron, maker of superb digital products."

name: chuckbergeron
markdown: kramdown
highlighter: rouge

exclude: ['deploy.sh', 'Gemfile', 'Gemfile.lock']
gems: [jekyll-assets, uglifier, jekyll-slim, slim]

assets:
  assets:
    - "application.css"
    - "*.svg"
    - "*.woff"
    - "*.woff2"
    - "*.eot"
    - "*.ttf"
    - "*.js"
    - "*.mp4"
    - "*.png"
    - "*.jpg"
    - "*.gif"
