# Site settings
title: Portfolio of Chuck Bergeron
email: chuck@chuckbergeron.io

name: chuckbergeron
description: "Chuck Bergeron creates VR experiences, videogames and apps in Vancouver, BC"
url: https://chuckbergeron.io

markdown: kramdown

paginate: 5
paginate_path: "/blog/page/:num"

exclude: ['deploy.sh', 'Gemfile', 'Gemfile.lock']
plugins: [jekyll-assets, uglifier, jekyll-paginate]

assets:
  assets:
    - "application.css"
    - "*.svg"
    - "*.woff"
    - "*.woff2"
    - "*.eot"
    - "*.ttf"
    - "*.js"
    - "*.mp4"
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.gif"
  sources:
    - assets/stylesheets
    - assets/fonts
    - assets/images
    - assets/videos
    - assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascripts
    - stylesheets
    - fonts
    - images
    - videos
    - javascripts

collections:
  work:
    output: true
    permalink: /:collection/:path/
